### PR TITLE
Component: Pet card to render info

### PR DESCRIPTION
**Pull request by FIOpwK**
## Description ##
 [x ] This is part of a feature.

This is a simple card component created to render pet's `data` from APIContext. 

## Review ##

- [ x] This is a work in progress.

Next task is to render Profile for pet that has correct customer_id.

### CODE REVIEW

**Review by linzyk86 — APPROVED** [review]
Looks like the T is missing in "temperament", but otherwise looks good!

**Comment by FIOpwK** [comment]
[As a pet owner, I would like to be able to create and see a profile for my pet.](https://trello.com/c/6c7YJ4IR/6-as-a-pet-owner-i-would-like-to-be-able-to-create-and-see-a-profile-for-my-pet)

**Comment by FIOpwK** [comment]
> Looks like the T is missing in "temperament", but otherwise looks good!

Good catch.  There's also note on `https://trello.com/c/6c7YJ4IR/` for an "age" feature. This is absent from APIContent.

**Review by davisblakep — APPROVED** [review]
Thanks for this! Looking forward to seeing the pets more incorporated into the overall project.

**Pull request merged**
