### PR TITLE
Refactored code for organizational purposes. Included fix for the okta widget.

### PR DESCRIPTION
**Pull request by davisblakep**
…a widget remove error.

## Description ##

DESCRIBE YOUR PULL REQUEST'S CHANGES AND REFERENCE THE FEATURE/USERSTORY/BUG IT'S REALATED TO.  REPLACE THIS TEXT.

## Type ##

- [x] This is a bugfix.
- [ ] This is a new feature.
- [ ] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?
- [x] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing 

## Review ##

- [ ] Is this a work in progress?
- [x] Is this ready to be reviewed?
- [x] Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by davisblakep** [comment]
[Reorganize the code file structure and folders for easier code visibility.](https://trello.com/c/BEcJY4ed/62-reorganize-the-code-file-structure-and-folders-for-easier-code-visibility)

**Comment by davisblakep** [comment]
[Reorganize the code file structure and folders for easier code visibility.](https://trello.com/c/BEcJY4ed/62-reorganize-the-code-file-structure-and-folders-for-easier-code-visibility)

**Comment by davisblakep** [comment]
[As a user, I would like to explore the website by clicking various links without the site crashing.](https://trello.com/c/tFgScUDB/60-as-a-user-i-would-like-to-explore-the-website-by-clicking-various-links-without-the-site-crashing)

**Review by jarrod847 — APPROVED** [review]

**Comment by FIOpwK** [comment]
Let's check the import failures on file names and paths.  Either  we rename everything to convention of NotFound  vs NotFoundPage; or update __tests__/ 

`FAIL src/__tests__/NotFoundPage.test.js
  ● Test suite failed to run

    Cannot find module '../components/pages/NotFound' from 'NotFoundPage.test.js'

      2 | import { render } from '@testing-library/react';
      3 | import { BrowserRouter as Router } from 'react-router-dom';
    > 4 | import { NotFoundPage } from '../components/pages/NotFound';
        | ^
      5 | 
      6 | describe('Loading Common Component', () => {
      7 |   test('it should mount a div based on props', () => {

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/__tests__/NotFoundPage.test.js:4:1)

FAIL src/__tests__/LoginContainer.test.js
  ● Test suite failed to run

    Cannot find module '../components/pages/Login/LoginContainer' from 'LoginContainer.test.js'

      2 | import { render } from '@testing-library/react';
      3 | 
    > 4 | import LoginContainer from '../components/pages/Login/LoginContainer';
`

**Comment by FIOpwK** [comment]
Can we also connect our github.trello.services with the repository. Each pull request will almost always have a trello card and user story we refer to in commit messages.

**Review by FIOpwK — APPROVED** [review]
Thank you @davisblakep

**Pull request merged**
